# Generated by Django 5.2.3 on 2025-07-03 02:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BundlePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bankName', models.CharField(max_length=100)),
                ('bankAccount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LogTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCourseBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCourseAmount', models.IntegerField()),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('bundlePrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_course_bundle_bundle_price', to='api.bundleprice')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_course_bundle_company', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('trainerName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('courseDateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('maxSeat', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('whatsappGroupLink', models.CharField(max_length=200)),
                ('hideOnFull', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hrdfClaimable', models.BooleanField()),
                ('courseCount', models.IntegerField()),
                ('tpCompanyFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_to_company', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='CourseBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseAmount', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_bundle_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bundleprice',
            name='courseBundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_price_course_bundle', to='api.coursebundle'),
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company_company', to='api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_course', to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
