# Generated by Django 5.2.3 on 2025-07-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bundleprice_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tpCompanyFk',
            new_name='company',
        ),
    ]
